"""initial schema: scenes, vehicles, frames, trust_records, criticality_records, decisions, experiments

Revision ID: b0fd54c927fe
Revises: 
Create Date: 2026-08-15 13:32:04.298849

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b0fd54c927fe'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('sync_overhead_ms', sa.Float(), nullable=True),
    sa.Column('energy_j', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_name'), 'experiments', ['name'], unique=True)
    op.create_table('scenes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_code', sa.String(length=128), nullable=False),
    sa.Column('map_name', sa.String(length=64), nullable=False),
    sa.Column('weather_preset', sa.String(length=64), nullable=False),
    sa.Column('num_vehicles_target', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_scene_code'), 'scenes', ['scene_code'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_code', sa.String(length=64), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), nullable=False),
    sa.Column('is_ego', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_scene_id'), 'vehicles', ['scene_id'], unique=False)
    op.create_table('frames',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('simulation_timestamp', sa.Float(), nullable=False),
    sa.Column('wireless_timestamp', sa.Float(), nullable=False),
    sa.Column('sync_timestamp', sa.Float(), nullable=False),
    sa.Column('sync_offset_ms', sa.Float(), nullable=False),
    sa.Column('is_sync_valid', sa.Boolean(), nullable=False),
    sa.Column('lidar_path', sa.String(length=512), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lon', sa.Float(), nullable=True),
    sa.Column('gps_alt', sa.Float(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('lane_id', sa.Integer(), nullable=True),
    sa.Column('imu_data', sa.JSON(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('csi', sa.JSON(), nullable=True),
    sa.Column('snr_db', sa.Float(), nullable=True),
    sa.Column('rssi_dbm', sa.Float(), nullable=True),
    sa.Column('path_loss_db', sa.Float(), nullable=True),
    sa.Column('beam_index', sa.Integer(), nullable=True),
    sa.Column('traffic_density', sa.Float(), nullable=True),
    sa.Column('weather', sa.String(length=64), nullable=True),
    sa.Column('mobility_state', sa.JSON(), nullable=True),
    sa.Column('environmental_context', sa.JSON(), nullable=True),
    sa.Column('prediction_uncertainty', sa.Float(), nullable=True),
    sa.Column('twin_age_ms', sa.Float(), nullable=True),
    sa.Column('gt_future_csi', sa.JSON(), nullable=True),
    sa.Column('gt_future_beam', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frames_scene_id'), 'frames', ['scene_id'], unique=False)
    op.create_index(op.f('ix_frames_vehicle_id'), 'frames', ['vehicle_id'], unique=False)
    op.create_table('criticality_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('frame_id', sa.UUID(), nullable=False),
    sa.Column('relative_speed_score', sa.Float(), nullable=False),
    sa.Column('blockage_probability_score', sa.Float(), nullable=False),
    sa.Column('sync_age_score', sa.Float(), nullable=False),
    sa.Column('channel_degradation_score', sa.Float(), nullable=False),
    sa.Column('traffic_density_score', sa.Float(), nullable=False),
    sa.Column('criticality_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criticality_records_frame_id'), 'criticality_records', ['frame_id'], unique=True)
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('frame_id', sa.UUID(), nullable=False),
    sa.Column('prediction_horizon', sa.Integer(), nullable=False),
    sa.Column('fsdp_action', sa.String(length=32), nullable=False),
    sa.Column('trust_probability_used', sa.Float(), nullable=False),
    sa.Column('criticality_score_used', sa.Float(), nullable=False),
    sa.Column('policy_source', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_frame_id'), 'decisions', ['frame_id'], unique=True)
    op.create_table('trust_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('frame_id', sa.UUID(), nullable=False),
    sa.Column('prediction_error', sa.Float(), nullable=False),
    sa.Column('prediction_uncertainty', sa.Float(), nullable=False),
    sa.Column('sync_age_penalty', sa.Float(), nullable=False),
    sa.Column('comm_quality', sa.Float(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('trust_probability', sa.Float(), nullable=False),
    sa.Column('interpretation', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_records_frame_id'), 'trust_records', ['frame_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trust_records_frame_id'), table_name='trust_records')
    op.drop_table('trust_records')
    op.drop_index(op.f('ix_decisions_frame_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_criticality_records_frame_id'), table_name='criticality_records')
    op.drop_table('criticality_records')
    op.drop_index(op.f('ix_frames_vehicle_id'), table_name='frames')
    op.drop_index(op.f('ix_frames_scene_id'), table_name='frames')
    op.drop_table('frames')
    op.drop_index(op.f('ix_vehicles_scene_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_scenes_scene_code'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_experiments_name'), table_name='experiments')
    op.drop_table('experiments')
    # ### end Alembic commands ###
